import {MigrationInterface, QueryRunner} from "typeorm";

export class Types1589224055573 implements MigrationInterface {
    name = 'Types1589224055573'

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `Administation` (`id` int NOT NULL AUTO_INCREMENT, `login` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `ItemDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `maxCount` int NOT NULL, `typeId` int NULL, `rarityId` int NULL, `currentVersionId` int NULL, UNIQUE INDEX `REL_ac3e3bf9e8d4ca65a3a272e5a1` (`currentVersionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `IngredientToRecipe` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `itemId` int NULL, `recipeId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `ResultToRecipe` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `dropChance` int NOT NULL, `itemId` int NULL, `recipeId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `IngredientToRecipeBuffer` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `itemId` int NULL, `recipeId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `ResultToRecipeBuffer` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `dropChance` int NOT NULL, `itemId` int NULL, `recipeId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `RecipeDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `currentVersionId` int NULL, UNIQUE INDEX `REL_75087211b2efefd9e5d2e2547f` (`currentVersionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `RecipeData` (`id` int NOT NULL AUTO_INCREMENT, `inRotation` tinyint NOT NULL, `updateBufferId` int NULL, UNIQUE INDEX `REL_b2bb44893e59e8f4329faac5b5` (`updateBufferId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `ItemData` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `inRotation` tinyint NOT NULL, `maxCount` int NOT NULL, `typeId` int NULL, `rarityId` int NULL, `updateBufferId` int NULL, UNIQUE INDEX `REL_af458cd1b82c57100c019ddf17` (`updateBufferId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `LocomotivesUpgradesData` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `level` int NOT NULL, `itemId` int NULL, `locomotiveDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `LocomotiveUpgradesDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `level` int NOT NULL, `itemId` int NULL, `locomotiveDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `LocomotivesBuildingSlotsDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `level` int NOT NULL, `buildingTypeId` int NULL, `locomotiveDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `LocomotiveDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `maxLevel` int NOT NULL, `currentVersionId` int NULL, UNIQUE INDEX `REL_52fc0054eb7c067bcb86207273` (`currentVersionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `LocomotiveData` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `maxLevel` int NOT NULL, `inRotation` tinyint NOT NULL, `updateBufferId` int NULL, UNIQUE INDEX `REL_d6d0a0f21c498e8f562cb0162b` (`updateBufferId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `LocomotivesBuildingSlotsData` (`id` int NOT NULL AUTO_INCREMENT, `level` int NOT NULL, `buildingTypeId` int NULL, `locomotiveDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `BuildingType` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `ItemsType` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `ItemsRarity` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `SectorData` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `positionX` int NOT NULL, `positionY` int NOT NULL, `updateBufferId` int NULL, UNIQUE INDEX `REL_2f69f57c03b98b0a162acf38d5` (`updateBufferId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `SectorDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `positionX` int NOT NULL, `positionY` int NOT NULL, `currentVersionId` int NULL, UNIQUE INDEX `REL_952a6778217093119815942fd4` (`currentVersionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `EnvironmentType` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `BuildingDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `size` int NOT NULL, `typeId` int NULL, `currentVersionId` int NULL, UNIQUE INDEX `REL_a7205a828f0c74d79fe7c52060` (`currentVersionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `BuildingData` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `size` int NOT NULL, `typeId` int NULL, `updateBufferId` int NULL, UNIQUE INDEX `REL_94b93980c6bd49b45e52d70b68` (`updateBufferId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `CarriageBuildingSlot` (`id` int NOT NULL AUTO_INCREMENT, `buildingSize` int NOT NULL, `buildingTypeId` int NULL, `carriageDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `CarriageAssemblyItemBufferData` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `itemId` int NULL, `carriageDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `CarriageBuildingSlotBuffer` (`id` int NOT NULL AUTO_INCREMENT, `buildingSize` int NOT NULL, `buildingTypeId` int NULL, `carriageDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `CarriageDataBuffer` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `storageCapacity` int NOT NULL, `crewCapacity` int NOT NULL, `currentVersionId` int NULL, UNIQUE INDEX `REL_851682d62c85225a900cf1fea1` (`currentVersionId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `CarriageData` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `inRotation` tinyint NOT NULL, `storageCapacity` int NOT NULL, `crewCapacity` int NOT NULL, `updateBufferId` int NULL, UNIQUE INDEX `REL_8f5ad542e9cb6fe703eacb4b9d` (`updateBufferId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `CarriageAssemblyItemData` (`id` int NOT NULL AUTO_INCREMENT, `count` int NOT NULL, `itemId` int NULL, `carriageDataId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `SectorDataToEnvironment` (`sectorDataId` int NOT NULL, `environmentTypeId` int NOT NULL, INDEX `IDX_8542dd39d8207d837519d0eb4c` (`sectorDataId`), INDEX `IDX_1454a13d380bb0354022fe7904` (`environmentTypeId`), PRIMARY KEY (`sectorDataId`, `environmentTypeId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `SectorDataBufferToEnvironment` (`sectorDataBufferId` int NOT NULL, `environmentTypeId` int NOT NULL, INDEX `IDX_189d9921175237170fa70c8fb3` (`sectorDataBufferId`), INDEX `IDX_54a7879644437fb12b332b6685` (`environmentTypeId`), PRIMARY KEY (`sectorDataBufferId`, `environmentTypeId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `RecipesToBuildingsBuffers` (`buildingDataBufferId` int NOT NULL, `recipeDataId` int NOT NULL, INDEX `IDX_c0235efb58479df7cba3c41143` (`buildingDataBufferId`), INDEX `IDX_387b76a27ae40a6c1fece32951` (`recipeDataId`), PRIMARY KEY (`buildingDataBufferId`, `recipeDataId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `RecipesToBuildings` (`buildingDataId` int NOT NULL, `recipeDataId` int NOT NULL, INDEX `IDX_5ba6c192b3f1a5e296d3abccbe` (`buildingDataId`), INDEX `IDX_9bae72471d8b509174e9c3de55` (`recipeDataId`), PRIMARY KEY (`buildingDataId`, `recipeDataId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("ALTER TABLE `ItemDataBuffer` ADD CONSTRAINT `FK_57d1838379fe20932dda5d4dab6` FOREIGN KEY (`typeId`) REFERENCES `ItemsType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ItemDataBuffer` ADD CONSTRAINT `FK_fef11c5c08291c76dcd29dc23ed` FOREIGN KEY (`rarityId`) REFERENCES `ItemsRarity`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ItemDataBuffer` ADD CONSTRAINT `FK_ac3e3bf9e8d4ca65a3a272e5a14` FOREIGN KEY (`currentVersionId`) REFERENCES `ItemData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipe` ADD CONSTRAINT `FK_e31957e96ced76df60e84fc3ebb` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipe` ADD CONSTRAINT `FK_aa95d26fb074883575c1f5b24c8` FOREIGN KEY (`recipeId`) REFERENCES `RecipeData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipe` ADD CONSTRAINT `FK_8bf20bfe720087f6e3cc7427391` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipe` ADD CONSTRAINT `FK_21ad950cabca84c6f964658bcc1` FOREIGN KEY (`recipeId`) REFERENCES `RecipeData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipeBuffer` ADD CONSTRAINT `FK_774c74a6a30f1abb8c987b2236a` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipeBuffer` ADD CONSTRAINT `FK_a9bcb81c00806666b6a59ce98e1` FOREIGN KEY (`recipeId`) REFERENCES `RecipeDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipeBuffer` ADD CONSTRAINT `FK_fed246b0250bc6da9557f1eed71` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipeBuffer` ADD CONSTRAINT `FK_197bd0f552a3ccb8290bde05757` FOREIGN KEY (`recipeId`) REFERENCES `RecipeDataBuffer`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `RecipeDataBuffer` ADD CONSTRAINT `FK_75087211b2efefd9e5d2e2547f9` FOREIGN KEY (`currentVersionId`) REFERENCES `RecipeData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `RecipeData` ADD CONSTRAINT `FK_b2bb44893e59e8f4329faac5b57` FOREIGN KEY (`updateBufferId`) REFERENCES `RecipeDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ItemData` ADD CONSTRAINT `FK_b905d23c37b299fa3a50607abb1` FOREIGN KEY (`typeId`) REFERENCES `ItemsType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ItemData` ADD CONSTRAINT `FK_cf2340ae96027b2d10bb9544794` FOREIGN KEY (`rarityId`) REFERENCES `ItemsRarity`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `ItemData` ADD CONSTRAINT `FK_af458cd1b82c57100c019ddf17c` FOREIGN KEY (`updateBufferId`) REFERENCES `ItemDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesUpgradesData` ADD CONSTRAINT `FK_53436a6478fb1cd328b3b62db7f` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesUpgradesData` ADD CONSTRAINT `FK_c1da8044632b31080ed8e9c8227` FOREIGN KEY (`locomotiveDataId`) REFERENCES `LocomotiveData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveUpgradesDataBuffer` ADD CONSTRAINT `FK_acd5a756428d973cca3a02a0178` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveUpgradesDataBuffer` ADD CONSTRAINT `FK_36bec8b29b2876ff227ceee8d84` FOREIGN KEY (`locomotiveDataId`) REFERENCES `LocomotiveDataBuffer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsDataBuffer` ADD CONSTRAINT `FK_c5e537eabe0ccfd8b15bd6e426b` FOREIGN KEY (`buildingTypeId`) REFERENCES `BuildingType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsDataBuffer` ADD CONSTRAINT `FK_fa3a599626f47a240053345021f` FOREIGN KEY (`locomotiveDataId`) REFERENCES `LocomotiveDataBuffer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveDataBuffer` ADD CONSTRAINT `FK_52fc0054eb7c067bcb862072736` FOREIGN KEY (`currentVersionId`) REFERENCES `LocomotiveData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveData` ADD CONSTRAINT `FK_d6d0a0f21c498e8f562cb0162be` FOREIGN KEY (`updateBufferId`) REFERENCES `LocomotiveDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsData` ADD CONSTRAINT `FK_de953894b58775f3f41b4d25236` FOREIGN KEY (`buildingTypeId`) REFERENCES `BuildingType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsData` ADD CONSTRAINT `FK_49093a65ad1ea24a39c8aea295d` FOREIGN KEY (`locomotiveDataId`) REFERENCES `LocomotiveData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `SectorData` ADD CONSTRAINT `FK_2f69f57c03b98b0a162acf38d51` FOREIGN KEY (`updateBufferId`) REFERENCES `SectorDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataBuffer` ADD CONSTRAINT `FK_952a6778217093119815942fd49` FOREIGN KEY (`currentVersionId`) REFERENCES `SectorData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `BuildingDataBuffer` ADD CONSTRAINT `FK_079091fa3b28dcae1cfafde7969` FOREIGN KEY (`typeId`) REFERENCES `BuildingType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `BuildingDataBuffer` ADD CONSTRAINT `FK_a7205a828f0c74d79fe7c52060f` FOREIGN KEY (`currentVersionId`) REFERENCES `BuildingData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `BuildingData` ADD CONSTRAINT `FK_021843de32be1a158431952c434` FOREIGN KEY (`typeId`) REFERENCES `BuildingType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `BuildingData` ADD CONSTRAINT `FK_94b93980c6bd49b45e52d70b68f` FOREIGN KEY (`updateBufferId`) REFERENCES `BuildingDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlot` ADD CONSTRAINT `FK_76ab60b438caafbefcc931b3493` FOREIGN KEY (`buildingTypeId`) REFERENCES `BuildingType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlot` ADD CONSTRAINT `FK_9e5575e5c4b4e1129b50e218d08` FOREIGN KEY (`carriageDataId`) REFERENCES `CarriageData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemBufferData` ADD CONSTRAINT `FK_78478c1ea2841e38d13b33c5322` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemBufferData` ADD CONSTRAINT `FK_3688539f35e73500bbc6f13c63a` FOREIGN KEY (`carriageDataId`) REFERENCES `CarriageDataBuffer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlotBuffer` ADD CONSTRAINT `FK_99bcf4ebf959911166ded9e21ae` FOREIGN KEY (`buildingTypeId`) REFERENCES `BuildingType`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlotBuffer` ADD CONSTRAINT `FK_0199956fc3866ab71ce4fc60a7e` FOREIGN KEY (`carriageDataId`) REFERENCES `CarriageDataBuffer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageDataBuffer` ADD CONSTRAINT `FK_851682d62c85225a900cf1fea1b` FOREIGN KEY (`currentVersionId`) REFERENCES `CarriageData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageData` ADD CONSTRAINT `FK_8f5ad542e9cb6fe703eacb4b9dd` FOREIGN KEY (`updateBufferId`) REFERENCES `CarriageDataBuffer`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemData` ADD CONSTRAINT `FK_824816e896edaa863148d2c71d6` FOREIGN KEY (`itemId`) REFERENCES `ItemData`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemData` ADD CONSTRAINT `FK_c86f8b3335c67675c26c5355be8` FOREIGN KEY (`carriageDataId`) REFERENCES `CarriageData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataToEnvironment` ADD CONSTRAINT `FK_8542dd39d8207d837519d0eb4c1` FOREIGN KEY (`sectorDataId`) REFERENCES `SectorData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataToEnvironment` ADD CONSTRAINT `FK_1454a13d380bb0354022fe79048` FOREIGN KEY (`environmentTypeId`) REFERENCES `EnvironmentType`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataBufferToEnvironment` ADD CONSTRAINT `FK_189d9921175237170fa70c8fb36` FOREIGN KEY (`sectorDataBufferId`) REFERENCES `SectorDataBuffer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataBufferToEnvironment` ADD CONSTRAINT `FK_54a7879644437fb12b332b6685a` FOREIGN KEY (`environmentTypeId`) REFERENCES `EnvironmentType`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildingsBuffers` ADD CONSTRAINT `FK_c0235efb58479df7cba3c41143a` FOREIGN KEY (`buildingDataBufferId`) REFERENCES `BuildingDataBuffer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildingsBuffers` ADD CONSTRAINT `FK_387b76a27ae40a6c1fece329513` FOREIGN KEY (`recipeDataId`) REFERENCES `RecipeData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildings` ADD CONSTRAINT `FK_5ba6c192b3f1a5e296d3abccbe2` FOREIGN KEY (`buildingDataId`) REFERENCES `BuildingData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildings` ADD CONSTRAINT `FK_9bae72471d8b509174e9c3de557` FOREIGN KEY (`recipeDataId`) REFERENCES `RecipeData`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("INSERT INTO `Administation`(`login`, `password`) VALUES (?, ?)", ["Test","$2y$12$FXjyohA9zMFOBWiOD0f85OrJJGvQbNH8v.h3Uxb3adw5L75GrvlNy"]);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `RecipesToBuildings` DROP FOREIGN KEY `FK_9bae72471d8b509174e9c3de557`", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildings` DROP FOREIGN KEY `FK_5ba6c192b3f1a5e296d3abccbe2`", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildingsBuffers` DROP FOREIGN KEY `FK_387b76a27ae40a6c1fece329513`", undefined);
        await queryRunner.query("ALTER TABLE `RecipesToBuildingsBuffers` DROP FOREIGN KEY `FK_c0235efb58479df7cba3c41143a`", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataBufferToEnvironment` DROP FOREIGN KEY `FK_54a7879644437fb12b332b6685a`", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataBufferToEnvironment` DROP FOREIGN KEY `FK_189d9921175237170fa70c8fb36`", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataToEnvironment` DROP FOREIGN KEY `FK_1454a13d380bb0354022fe79048`", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataToEnvironment` DROP FOREIGN KEY `FK_8542dd39d8207d837519d0eb4c1`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemData` DROP FOREIGN KEY `FK_c86f8b3335c67675c26c5355be8`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemData` DROP FOREIGN KEY `FK_824816e896edaa863148d2c71d6`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageData` DROP FOREIGN KEY `FK_8f5ad542e9cb6fe703eacb4b9dd`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageDataBuffer` DROP FOREIGN KEY `FK_851682d62c85225a900cf1fea1b`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlotBuffer` DROP FOREIGN KEY `FK_0199956fc3866ab71ce4fc60a7e`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlotBuffer` DROP FOREIGN KEY `FK_99bcf4ebf959911166ded9e21ae`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemBufferData` DROP FOREIGN KEY `FK_3688539f35e73500bbc6f13c63a`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageAssemblyItemBufferData` DROP FOREIGN KEY `FK_78478c1ea2841e38d13b33c5322`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlot` DROP FOREIGN KEY `FK_9e5575e5c4b4e1129b50e218d08`", undefined);
        await queryRunner.query("ALTER TABLE `CarriageBuildingSlot` DROP FOREIGN KEY `FK_76ab60b438caafbefcc931b3493`", undefined);
        await queryRunner.query("ALTER TABLE `BuildingData` DROP FOREIGN KEY `FK_94b93980c6bd49b45e52d70b68f`", undefined);
        await queryRunner.query("ALTER TABLE `BuildingData` DROP FOREIGN KEY `FK_021843de32be1a158431952c434`", undefined);
        await queryRunner.query("ALTER TABLE `BuildingDataBuffer` DROP FOREIGN KEY `FK_a7205a828f0c74d79fe7c52060f`", undefined);
        await queryRunner.query("ALTER TABLE `BuildingDataBuffer` DROP FOREIGN KEY `FK_079091fa3b28dcae1cfafde7969`", undefined);
        await queryRunner.query("ALTER TABLE `SectorDataBuffer` DROP FOREIGN KEY `FK_952a6778217093119815942fd49`", undefined);
        await queryRunner.query("ALTER TABLE `SectorData` DROP FOREIGN KEY `FK_2f69f57c03b98b0a162acf38d51`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsData` DROP FOREIGN KEY `FK_49093a65ad1ea24a39c8aea295d`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsData` DROP FOREIGN KEY `FK_de953894b58775f3f41b4d25236`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveData` DROP FOREIGN KEY `FK_d6d0a0f21c498e8f562cb0162be`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveDataBuffer` DROP FOREIGN KEY `FK_52fc0054eb7c067bcb862072736`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsDataBuffer` DROP FOREIGN KEY `FK_fa3a599626f47a240053345021f`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesBuildingSlotsDataBuffer` DROP FOREIGN KEY `FK_c5e537eabe0ccfd8b15bd6e426b`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveUpgradesDataBuffer` DROP FOREIGN KEY `FK_36bec8b29b2876ff227ceee8d84`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotiveUpgradesDataBuffer` DROP FOREIGN KEY `FK_acd5a756428d973cca3a02a0178`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesUpgradesData` DROP FOREIGN KEY `FK_c1da8044632b31080ed8e9c8227`", undefined);
        await queryRunner.query("ALTER TABLE `LocomotivesUpgradesData` DROP FOREIGN KEY `FK_53436a6478fb1cd328b3b62db7f`", undefined);
        await queryRunner.query("ALTER TABLE `ItemData` DROP FOREIGN KEY `FK_af458cd1b82c57100c019ddf17c`", undefined);
        await queryRunner.query("ALTER TABLE `ItemData` DROP FOREIGN KEY `FK_cf2340ae96027b2d10bb9544794`", undefined);
        await queryRunner.query("ALTER TABLE `ItemData` DROP FOREIGN KEY `FK_b905d23c37b299fa3a50607abb1`", undefined);
        await queryRunner.query("ALTER TABLE `RecipeData` DROP FOREIGN KEY `FK_b2bb44893e59e8f4329faac5b57`", undefined);
        await queryRunner.query("ALTER TABLE `RecipeDataBuffer` DROP FOREIGN KEY `FK_75087211b2efefd9e5d2e2547f9`", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipeBuffer` DROP FOREIGN KEY `FK_197bd0f552a3ccb8290bde05757`", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipeBuffer` DROP FOREIGN KEY `FK_fed246b0250bc6da9557f1eed71`", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipeBuffer` DROP FOREIGN KEY `FK_a9bcb81c00806666b6a59ce98e1`", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipeBuffer` DROP FOREIGN KEY `FK_774c74a6a30f1abb8c987b2236a`", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipe` DROP FOREIGN KEY `FK_21ad950cabca84c6f964658bcc1`", undefined);
        await queryRunner.query("ALTER TABLE `ResultToRecipe` DROP FOREIGN KEY `FK_8bf20bfe720087f6e3cc7427391`", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipe` DROP FOREIGN KEY `FK_aa95d26fb074883575c1f5b24c8`", undefined);
        await queryRunner.query("ALTER TABLE `IngredientToRecipe` DROP FOREIGN KEY `FK_e31957e96ced76df60e84fc3ebb`", undefined);
        await queryRunner.query("ALTER TABLE `ItemDataBuffer` DROP FOREIGN KEY `FK_ac3e3bf9e8d4ca65a3a272e5a14`", undefined);
        await queryRunner.query("ALTER TABLE `ItemDataBuffer` DROP FOREIGN KEY `FK_fef11c5c08291c76dcd29dc23ed`", undefined);
        await queryRunner.query("ALTER TABLE `ItemDataBuffer` DROP FOREIGN KEY `FK_57d1838379fe20932dda5d4dab6`", undefined);
        await queryRunner.query("DROP INDEX `IDX_9bae72471d8b509174e9c3de55` ON `RecipesToBuildings`", undefined);
        await queryRunner.query("DROP INDEX `IDX_5ba6c192b3f1a5e296d3abccbe` ON `RecipesToBuildings`", undefined);
        await queryRunner.query("DROP TABLE `RecipesToBuildings`", undefined);
        await queryRunner.query("DROP INDEX `IDX_387b76a27ae40a6c1fece32951` ON `RecipesToBuildingsBuffers`", undefined);
        await queryRunner.query("DROP INDEX `IDX_c0235efb58479df7cba3c41143` ON `RecipesToBuildingsBuffers`", undefined);
        await queryRunner.query("DROP TABLE `RecipesToBuildingsBuffers`", undefined);
        await queryRunner.query("DROP INDEX `IDX_54a7879644437fb12b332b6685` ON `SectorDataBufferToEnvironment`", undefined);
        await queryRunner.query("DROP INDEX `IDX_189d9921175237170fa70c8fb3` ON `SectorDataBufferToEnvironment`", undefined);
        await queryRunner.query("DROP TABLE `SectorDataBufferToEnvironment`", undefined);
        await queryRunner.query("DROP INDEX `IDX_1454a13d380bb0354022fe7904` ON `SectorDataToEnvironment`", undefined);
        await queryRunner.query("DROP INDEX `IDX_8542dd39d8207d837519d0eb4c` ON `SectorDataToEnvironment`", undefined);
        await queryRunner.query("DROP TABLE `SectorDataToEnvironment`", undefined);
        await queryRunner.query("DROP TABLE `CarriageAssemblyItemData`", undefined);
        await queryRunner.query("DROP INDEX `REL_8f5ad542e9cb6fe703eacb4b9d` ON `CarriageData`", undefined);
        await queryRunner.query("DROP TABLE `CarriageData`", undefined);
        await queryRunner.query("DROP INDEX `REL_851682d62c85225a900cf1fea1` ON `CarriageDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `CarriageDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `CarriageBuildingSlotBuffer`", undefined);
        await queryRunner.query("DROP TABLE `CarriageAssemblyItemBufferData`", undefined);
        await queryRunner.query("DROP TABLE `CarriageBuildingSlot`", undefined);
        await queryRunner.query("DROP INDEX `REL_94b93980c6bd49b45e52d70b68` ON `BuildingData`", undefined);
        await queryRunner.query("DROP TABLE `BuildingData`", undefined);
        await queryRunner.query("DROP INDEX `REL_a7205a828f0c74d79fe7c52060` ON `BuildingDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `BuildingDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `EnvironmentType`", undefined);
        await queryRunner.query("DROP INDEX `REL_952a6778217093119815942fd4` ON `SectorDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `SectorDataBuffer`", undefined);
        await queryRunner.query("DROP INDEX `REL_2f69f57c03b98b0a162acf38d5` ON `SectorData`", undefined);
        await queryRunner.query("DROP TABLE `SectorData`", undefined);
        await queryRunner.query("DROP TABLE `ItemsRarity`", undefined);
        await queryRunner.query("DROP TABLE `ItemsType`", undefined);
        await queryRunner.query("DROP TABLE `BuildingType`", undefined);
        await queryRunner.query("DROP TABLE `LocomotivesBuildingSlotsData`", undefined);
        await queryRunner.query("DROP INDEX `REL_d6d0a0f21c498e8f562cb0162b` ON `LocomotiveData`", undefined);
        await queryRunner.query("DROP TABLE `LocomotiveData`", undefined);
        await queryRunner.query("DROP INDEX `REL_52fc0054eb7c067bcb86207273` ON `LocomotiveDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `LocomotiveDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `LocomotivesBuildingSlotsDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `LocomotiveUpgradesDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `LocomotivesUpgradesData`", undefined);
        await queryRunner.query("DROP INDEX `REL_af458cd1b82c57100c019ddf17` ON `ItemData`", undefined);
        await queryRunner.query("DROP TABLE `ItemData`", undefined);
        await queryRunner.query("DROP INDEX `REL_b2bb44893e59e8f4329faac5b5` ON `RecipeData`", undefined);
        await queryRunner.query("DROP TABLE `RecipeData`", undefined);
        await queryRunner.query("DROP INDEX `REL_75087211b2efefd9e5d2e2547f` ON `RecipeDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `RecipeDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `ResultToRecipeBuffer`", undefined);
        await queryRunner.query("DROP TABLE `IngredientToRecipeBuffer`", undefined);
        await queryRunner.query("DROP TABLE `ResultToRecipe`", undefined);
        await queryRunner.query("DROP TABLE `IngredientToRecipe`", undefined);
        await queryRunner.query("DROP INDEX `REL_ac3e3bf9e8d4ca65a3a272e5a1` ON `ItemDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `ItemDataBuffer`", undefined);
        await queryRunner.query("DROP TABLE `Administation`", undefined);
    }

}
